/*
 * Copyright (c) 2025 Ivan Kniazkov
 */
package com.kniazkov.widgets;

/**
 * Interface for logging server messages.
 * <p>
 *     Implementations of this interface are responsible for recording diagnostic,
 *     informational, or error messages generated by the application.
 * </p>
 */
public interface Logger {

    /**
     * Writes a message to the log output.
     *
     * @param message The message to log
     */
    void write(String message);
}
